wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [50, 68, 62]
    rows: [12, 10, 6, 5]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    sports:
      cmd: "$HOME/.config/utils/sports.sh"
      args: []
      enabled: true
      refreshInterval: 300
      title: "üèü Today's Games"
      type: cmdrunner
      position:
        top: 0
        left: 0
        height: 2
        width: 1
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 10
      storyType: top
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      refreshInterval: 900
    clocks:
      type: clocks
      title: "Clocks"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Baltimore: "America/New_York"
        San_Francisco: "America/Los_Angeles"
        Phoenix: "America/Phoenix"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 150
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
    uptime:
      type: cmdrunner
      cmd: "uptime"
      args: []
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 2
      refreshInterval: 30
    battery:
      type: power
      title: "‚ö°Ô∏è Battery"
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 2
      refreshInterval: 15
