wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [50, 68, 62]
    rows: [12, 6, 6, 6, 5]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    weather:
      type: cmdrunner
      cmd: "/Users/gavin/.config/utils/weather.sh"
      args: []
      enabled: true
      title: "‚õÖ Weather"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 1800
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 10
      storyType: top
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      refreshInterval: 900
    sports:
      type: cmdrunner
      cmd: "/Users/gavin/.config/utils/sports.sh"
      args: []
      enabled: true
      title: "üèü Today's Games"
      position:
        top: 1
        left: 0
        height: 2
        width: 1
      refreshInterval: 300
    clocks:
      type: clocks
      title: "Clocks"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        French_Alps: "Europe/Paris"
        Baltimore: "America/New_York"
        Phoenix: "America/Phoenix"
        San_Francisco: "America/Los_Angeles"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "reversechronological"
    btc:
      type: cmdrunner
      cmd: "/Users/gavin/.config/utils/btc.sh"
      args: []
      enabled: true
      title: "‚Çø Bitcoin"
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 300
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 2
        height: 2
        width: 1
      refreshInterval: 150
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
    battery:
      type: power
      title: "‚ö°Ô∏è Battery"
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
    security:
      type: security
      title: "üîí Security"
      enabled: true
      position:
        top: 3
        left: 2
        height: 2
        width: 1
      refreshInterval: 3600
    uptime:
      type: cmdrunner
      cmd: "uptime"
      args: []
      enabled: true
      position:
        top: 4
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
